/**
 * Chat and Conversation Constants
 *
 * Stable timing constants used by chat UI debouncing and download feedback.
 * Conversation/message IDs are now generated by the Rust DB layer; nothing
 * in this file mints them.
 */

/**
 * CONVERSATION_SAVE_DEBOUNCE_MS
 *
 * Debounce delay for the system-audio conversation auto-sync. The sync diffs
 * persisted vs in-memory message IDs and appends only the new ones.
 *
 * 500ms balances responsiveness with avoiding write storms.
 */
export const CONVERSATION_SAVE_DEBOUNCE_MS = 500;

/**
 * CHUNK_POLL_INTERVAL_MS
 *
 * How frequently to check for new streaming chunks from Pluely API.
 *
 * 50ms provides smooth streaming without excessive CPU usage.
 */
export const CHUNK_POLL_INTERVAL_MS = 50;

/**
 * DOWNLOAD_SUCCESS_DISPLAY_MS
 *
 * How long the "Downloaded" / "Attached" feedback indicator stays visible
 * before reverting.
 */
export const DOWNLOAD_SUCCESS_DISPLAY_MS = 1000;

/**
 * Generate a unique request ID for tracking in-flight API calls. Purely a
 * client-side correlation id; never persisted.
 */
export function generateRequestId(): string {
  const timestamp = Date.now();
  const random = Math.random().toString(36).substring(2, 11);
  return `req_${timestamp}_${random}`;
}
