/**
 * Chat and Conversation Constants
 *
 * Stable timing constants used by chat UI debouncing and download feedback.
 * Conversation/message IDs are generated by the Rust DB layer; LLM
 * request IDs are minted by `generateRequestId` in `lib/llm`.
 */

/**
 * CONVERSATION_SAVE_DEBOUNCE_MS
 *
 * Debounce delay for the system-audio conversation auto-sync. The sync diffs
 * persisted vs in-memory message IDs and appends only the new ones.
 *
 * 500ms balances responsiveness with avoiding write storms.
 */
export const CONVERSATION_SAVE_DEBOUNCE_MS = 500;

/**
 * DOWNLOAD_SUCCESS_DISPLAY_MS
 *
 * How long the "Downloaded" / "Attached" feedback indicator stays visible
 * before reverting.
 */
export const DOWNLOAD_SUCCESS_DISPLAY_MS = 1000;
