/**
 * Chat and Conversation Constants
 *
 * Stable timing constants used by chat UI debouncing and download feedback.
 * Conversation/message IDs are generated by the Rust DB layer; LLM
 * request IDs are minted by `generateRequestId` in `lib/llm`.
 */

/**
 * DOWNLOAD_SUCCESS_DISPLAY_MS
 *
 * How long the "Downloaded" / "Attached" feedback indicator stays visible
 * before reverting.
 */
export const DOWNLOAD_SUCCESS_DISPLAY_MS = 1000;
